import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from 'react-hot-toast'
import Toastcontext from './context/Toastcontext'
import { SessionProvider } from 'next-auth/react'
import Authcontext from './context/Authcontext'
import ActiveStatus from './components/Activestatus'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'OrientTalk',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <Authcontext>
        <Toastcontext/> 
        <ActiveStatus/>
        {children}
        </Authcontext>
        </body>
      
    </html>
  )
}
